#!/bin/bash

echo 'Revision $Id$'

[[ $# != 1 ]] && echo Usage: w3wkey=xxxxxxxx extract file.gpx && exit

file=$1

[[ x$w3wkey == x ]] && echo No key && exit

echo Reading file $file

while read -r line
do
	unset latitude
	unset longitude

	# Extract lat/long
	[[ $line =~ lat\=\"([0-9\.\-]*) ]] && latitude=${BASH_REMATCH[1]}
	[[ $line =~ lon\=\"([0-9\.\-]*) ]] && longitude=${BASH_REMATCH[1]}

	# Check we found a match
	if [[ x$latitude != x ]]
	then
		# Fetch w3w
		lwp-request "https://api.what3words.com/position?key=$w3wkey&position=$latitude,$longitude&lang=en"
		echo
	fi

done < $file
